version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    command: ['postgres', '-c', 'log_statement=all']
    restart: always
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '5434:5432'